language: python
services:
    - redis-server
python:
    - "3.4"
    - "3.5"
install:
    - "pip install -r requirements.txt"
    - "pip install https://github.com/eternnoir/pywit/archive/master.zip"
script:
    - cd tests && py.test
